### ISSUE TITLE
Create how_lit_db Database and tables

### ISSUE THREAD

**Issue by stcalica** [stcalica/HowLit#3]
create the database and tables

**Comment by psmith586** [comment]
added a mysql script to build the db. doesn't have anything to populate the info yet.

**Comment by psmith586** [comment]
add and subtract fields as necessary

**Comment by stcalica** [comment]
cool. ill run it later. good shit. will test at our minihackathon

**Comment by stcalica** [comment]
worked well, tables and info is all in. need to init it all now and then it will be all coo
